version: '3.4'

services:
  arcus.messaging.tests.worker:
    environment:
      - ARCUS_HEALTH_PORT=5001
      - ARCUS_SERVICEBUS_QUEUE_CONNECTIONSTRING=Endpoint=sb://arcus-messaging-dev-we-integration-tests.servicebus.windows.net/;SharedAccessKeyName=Integration-Tests;SharedAccessKey=ySk88As/NZclNHWu1flBf0BYvgrzV6+/I9yZ+b7r3j8=;EntityPath=orders
      - EVENTGRID_TOPIC_URI=https://arcus-event-grid-dev-we-integration-tests.westeurope-1.eventgrid.azure.net/api/events
      - EVENTGRID_AUTH_KEY=B7rqeccGOOhhI0arirZNx5fyM/yJ2RZizPsybLZXkMI=
    ports:
      - '42063:5001'
